### ISSUE TITLE
Fix Post Image Wrapper CSS

### ISSUE THREAD

**Issue by intfract** [dotargz/kynosocial#33]
**It is very common for the usernames to wrap in a post!**

I forked this repository so I could work on some changes to the CSS. I will try increasing the padding of things so it isn't so clustered. Hopefully I can make it more modern and clean because in my opinion, the `box-shadow` stuff is a bit excessive. We need to introduce an accent color to make things look interesting.

**Comment by foxlldev** [comment]
could you pls be more like "you guys should introduce..." not "we need to..."
also, the box shadow is there for dark theme (looks ew without, ill decrease soontm)

**Comment by intfract** [comment]
what does soontm mean
