### ISSUE TITLE
Style Guide 

### ISSUE THREAD

**Issue by nodexninja** [dotargz/kynosocial#6]
# Style Guide 

## CSS Theme 

We need to develop a **universal theme** for kynosocial before we go too far. A good look is essential to social media platforms. We might need to adopt a **dark mode** feature as well. 

## Palette 

Someone has to decide a **colour palette**. This website desperately needs one. Don't forget to consider dark mode compatibility as well. 

## Design 

We need to think of a good UI design for kynosocial and implement responsive CSS code. I suggest taking a page out of the **material design** book.

**Comment by foxlldev** [comment]
universal theme? heh? we've done themes, you can find them in your account's settings page. dark mode coming soon.
our color pallete is black + white. our themes systems supports color schemes like 'modern, yellow' and 'modern, blue'. these change the background (and other) colors, but do not alter other styling.
when you open kynosocial you are looking at the ui design - that's it. if you'd like it to be different, feel free to make it yourself and create a pull request.
as for needing the 'responsive CSS code', we have one - the main section of the site is constrained to a max width of something like 800px, and gets smaller on smaller screen sizes.

also, your tone here sounds quite condescending, as if we do not know what we are doing. a better phrasing of your issues with the site would be appreciated.

thank you for your ideas.

**Comment by Wjplatformer** [comment]
I can create themes for EVERYONE :)

**Comment by foxlldev** [comment]
Closing due to 90% of points being invalid

**Comment by Wjplatformer** [comment]
okie guy

**Comment by foxlldev** [comment]
we now have a dark theme: 'hyper' theme
