### ISSUE TITLE
Text truncated with trailing HTML tags

### ISSUE THREAD

**Issue by devxan** [dotargz/kynosocial#9]
What I see on the [Trending page](https://kyno.social/?page=trending&section=2)
![kyno bug](https://user-images.githubusercontent.com/57809064/192847171-529ef390-3934-4f19-81a3-c62b1103ba7b.png)
What I see on the [post page](https://kyno.social/?page=post&post=4zbfed2f6j7lq0v)
![kyno buggy](https://user-images.githubusercontent.com/57809064/192847345-1c241eea-7af0-4490-8a6e-0f879723c376.png)
Something's up with how the post is being shown. @dotargz (@Wjplatformer)

**Comment by dotargz** [comment]
ah yes
this is something i noticed

the text is being truncated with a trailing link

**Comment by dotargz** [comment]
A fix to this would be creating a smart truncate function that notices trailing html tags and ends them.

**Comment by devxan** [comment]
Also can I have Bug Hunter badge? 🎖

**Comment by Wjplatformer** [comment]
Hello. I noticed this bug too. But too lazy to report it lol. Anyways, wth is a trailing html tag

**Comment by foxlldev** [comment]
will fix soontm

**Comment by foxlldev** [comment]
this is hard af turns out
see https://stackoverflow.com/questions/34631125/truncating-text-in-javascript-excluding-html-elements
